### ISSUE TITLE
Add Sinhala Numerals

### ISSUE THREAD

**Issue by pathumego** [mooniak/abhaya-libre-font#13]
Unicode 7 added 2 sets of Sinhala traditional numerals to the Unicode block. This should be added. This was omitted form the initial release because we needed to do more testing on how these should be designed proportionally.  
- http://unicode.org/charts/PDF/U0D80.pdf
- http://unicode.org/charts/PDF/U111E0.pdf

These could be added to SS2 set I think.

**Comment by pathumego** [comment]
Early printed documents from 1730–1790 Dutch Ceylon govt press is the best reference point for this in my opinion. We can look at samples from manuscripts, but given the historical nature of these letterforms, we will do a bit of a research before diving into this.

**Comment by kosalaya** [comment]
I'm adding the following draft design for recording purposes and to get any comments and suggestions before final implementation of Lith Numerals in Abhaya Libre.

Based on the limited references* available, I decided to implements the same symbol as Letter Ja (ජ) for number 4, Letter Da (ද) for number 5 and Letter Ra (ර) for number 8.

I have 2 suggestions for Number 7 based on the same references. I suggest we select the one that closely represents the characteristics of Abhaya Libre as both forms are considered not wrong. Open for discussion.

*The shapes I referred were found in the book 'Numerations in the Sinhala Language' by Harsha Wijayawardhana and the The Unicode Standard, Version 13.0.

<img width="1239" alt="Screenshot 2021-06-07 at 19 19 08" src="https://user-images.githubusercontent.com/8073976/121473218-f168cf80-c9df-11eb-8f5f-d90aeb386c51.png">
<img width="830" alt="Screenshot 2021-06-10 at 11 11 18" src="https://user-images.githubusercontent.com/8073976/121473244-fd549180-c9df-11eb-8a3b-2d65fd37dcf1.png">

**Comment by JanakaCB** [comment]
@kosalaya First of all, thank you very much for your efforts in adding these glyphs into the Abhaya Libre. 

Second, I got some suggestions which I think you may consider in improving the overall harmony in-between other glyphs and these numerals.

1. As we both know, the glyph which represents zero here is conceptually identical with the halanth figure, why don't we use the same vertical halanth form of the Abhaya Libre for this instance? 

2. Moreover, I think there should be nine other glyphs designed combining this zero halanth form with other nine numerals, as it is the way it was used in writing numbers like 10, 20, etc. 

3. It is clearly seen from the sources you've uploaded that there is an 'eye shape' in the beginning of the shape which represents number six. So shall we add that feature into 'glyph six' as we can see almost all the glyphs of the font preserve that uniqueness of the language?

4. The glyph representing number 9 connotates the shape of  'නී' . So in the usage, the above part of the 'glyph nine' is similar to an ispilla. Hence, it is better making both shapes touched (the ispilla part of the glyph with the 'na part' of the glyph) at the end of the glyph as we've used ispilla in that way all over the font.

**Comment by JanakaCB** [comment]
> 
> I have 2 suggestions for Number 7 based on the same references. I suggest we select the one that closely represents the characteristics of Abhaya Libre as both forms are considered not wrong. Open for discussion.
> 

I think it is clear that we should select Uyanna (උ) in this matter. There are adequate references which clearly states that it is උ, including the one you mentioned 'Numerations in the Sinhala Language' by Harsha Wijayawardhana. The image below is an extraction from a pdf copy of the above said Mr. Harsha's book.


![Screenshot 2021-06-16 125112](https://user-images.githubusercontent.com/13979985/122177316-1e672780-cea3-11eb-893a-da8067511e38.jpg)

**Comment by JanakaCB** [comment]
Just for the beneficence of future researches, I think I should mention about a misconception of the word 'Akma' (ඇක්ම) used to name number 6 in the set of Lith numerals. 

ඇක්ම is the term always used to identify the shape of number 6. But I've seen some people use this word as a synonym to ඇදය (the vowel sign), probably due to the connotation of 'ඇ' sound in the word. But, as far as I got to know, ඇක්ම is the word for number 6, and number 6 is not close to the shape of ඇදය. 

However, there was only one source which cleared this chaos, which is shown in the below image from the book 'අභිනව ලිත් හෝඩිය සහ මුහුර්ත සාධනය' by Modern Publishers of Nugegoda.

![IMG_20210610_221244](https://user-images.githubusercontent.com/13979985/122185861-1317fa00-ceab-11eb-85a6-198400bd7884.jpg)

According to that I think, sometimes, this image may shows an earlier usage which changed later due to the possible confusions happened in distinguishing number 6 and 7 in handwritten documents. I suggest there should be more in-depth researches in this field for an entirely clear picture.

ජයවේවා෴
