### ISSUE TITLE
TTFs

### ISSUE THREAD

**Issue by davelab6** [mooniak/abhaya-libre-font#38]
Okay, I uploaded v1.030 to Googel Fonts here, https://github.com/google/fonts/commit/2076d77e03956b0c7a30d1b80798e771b0e663a7

<img width="1920" alt="screen shot 2016-01-28 at 09 51 13" src="https://cloud.githubusercontent.com/assets/261579/12647771/e472a7e6-c5a4-11e5-9c72-e69d56cdb4e4.png">
<img width="1920" alt="screen shot 2016-01-28 at 09 51 17" src="https://cloud.githubusercontent.com/assets/261579/12647770/e472a8c2-c5a4-11e5-849e-fc8e882038b4.png">
<img width="1920" alt="screen shot 2016-01-28 at 09 51 20" src="https://cloud.githubusercontent.com/assets/261579/12647772/e47661b0-c5a4-11e5-8cfa-54386965299b.png">

But looking carefully at the shaping, it seems only Firefox is shaping it well. Is this true?

**Comment by pathumego** [comment]
@davelab6 Yes,  Safari is not supporting yet. But I think a recent webkit update fixed it. 

In your screenshot Chrome is partially rendering. WIthout rakar, reph and yansaya rendering. This was the case before Chrome 39. But now It should work properly. Whats the chrome version?

![screen shot 2016-01-28 at 3 02 44 pm](https://cloud.githubusercontent.com/assets/6846609/12648157/82a80516-c5d0-11e5-8ec0-fdc33b4b6999.png)

**Comment by davelab6** [comment]
Chrome Canary - Version 50.0.2633.0 canary (64-bit)

**Comment by pathumego** [comment]
Ok its broken on Canary for mee too. But cheks out on other browsers

**Comment by pathumego** [comment]
@davelab6 This is unresolved I think you broke some things when processing ttf's. Now only FF is rendering the JSbin properly. Our testing page renders everything properly at http://mooniak.com/abhaya-libre-font/tests/ on both mac canary `Version 50.0.2661.0 canary (64-bit)` and chrome `Version 48.0.2564.116 (64-bit)` But your JSbin served from sandbox is broken on both, just like before. I think earlier it was working on Chrome stable because It was serving local file I had installed. My mistake. Can you chek the files again? What's not working is rakar and reph features,

**Comment by pathumego** [comment]
Ok its getting weird now, I downloaded the ttf's from your commit. On Chrome same version It works properly on Imapllari testing page.

**Comment by davelab6** [comment]
Please build TTFs and I will onboard them. :)

**Comment by davelab6** [comment]
What's the latest status on building TTFs?

**Comment by pathumego** [comment]
DONE https://github.com/mooniak/abhaya-libre-font/releases/tag/1.040
