### ISSUE TITLE
Some letters are not rendering properly on Ubuntu.

### ISSUE THREAD

**Issue by ssudaraka** [mooniak/abhaya-libre-font#43]
I've added Abhaya font set as default fonts in my Ubuntu. (I'm using version 14.04) and some letters are not showing properly. When I've changed the font to Malithi, it worked fine. Screenshots are attached. 

I think problem is with Kombuwa.
Text is just random, don't mind about what is says. 

With Abhaya font v1.040
![screenshot from 2016-05-07 21 52 26](https://cloud.githubusercontent.com/assets/7452912/15093231/bebe3e5e-149e-11e6-9058-5d9d78dc20b6.png)

With Malithi font
![malithiscreenshot from 2016-05-07 21 54 06](https://cloud.githubusercontent.com/assets/7452912/15093236/dd538aea-149e-11e6-8ec0-ecc11e4aaa47.png)

**Comment by pathumego** [comment]
@ssudaraka On which software is this?

**Comment by ssudaraka** [comment]
Mozilla Firefox (46.0) for Ubuntu Canonical.

**Comment by pathumego** [comment]
I tested this with v1.040 and reproduced. We had a interpolations problem with ` ෝ ` on the v1.030. Because of the glyph decomposition on other platforms it renders properly but on Linux Harfbuzz seems to do this differently. Anyway v1.050 will be out this week and it should fix this problem. I will post a bug on Harfbuzz to clarify this.

**Comment by pathumego** [comment]
@ssudaraka Please check the v1.050. it fixes this issue
